<a href="https://colab.research.google.com/github/keidenmw21-prog/MIS433/blob/main/Panda_Data_Manipulation_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Manipulation in Pandas

In this assignment, you will be working on the same dataframe of flights departing New York City in 2013.

In [31]:
import pandas as pd
import numpy as np

In [32]:
pip install nycflights13

Requirement already satisfied: nycflights13 in /usr/local/lib/python3.12/dist-packages (0.0.3)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from nycflights13) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.24.0->nycflights13) (1.17.0)

In [33]:
# Install the package 'nycflights13' before you can run this
from nycflights13 import flights
flights.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,distance,hour,minute,time_hour,dep_time_mins,sched_dep_time_mins,arrd_time_mins,dep_delay_calc,arr_time_mins,airdep_time_diff
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,...,1400,5,15,2013-01-01T10:00:00Z,317.0,315,510.0,2.0,510.0,193.0
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,...,1416,5,29,2013-01-01T10:00:00Z,333.0,329,530.0,4.0,530.0,197.0
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,...,1089,5,40,2013-01-01T10:00:00Z,342.0,340,563.0,2.0,563.0,221.0
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,...,1576,5,45,2013-01-01T10:00:00Z,344.0,345,604.0,-1.0,604.0,260.0
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,...,762,6,0,2013-01-01T11:00:00Z,354.0,360,492.0,-6.0,492.0,138.0

In [34]:
flights.shape

(336776, 25)

In [35]:
list(flights.columns)

['year',
 'month',
 'day',
 'dep_time',
 'sched_dep_time',
 'dep_delay',
 'arr_time',
 'sched_arr_time',
 'arr_delay',
 'carrier',
 'flight',
 'tailnum',
 'origin',
 'dest',
 'air_time',
 'distance',
 'hour',
 'minute',
 'time_hour',
 'dep_time_mins',
 'sched_dep_time_mins',
 'arrd_time_mins',
 'dep_delay_calc',
 'arr_time_mins',
 'airdep_time_diff']

## Data frame with columns

- year,month,day
        Date of departure    
- dep_time,arr_time
        Actual departure and arrival times (format HHMM or HMM), local tz.
- sched_dep_time,sched_arr_time
        Scheduled departure and arrival times (format HHMM or HMM), local tz.    
- dep_delay,arr_delay
        Departure and arrival delays, in minutes. Negative times represent early departures/arrivals.
- hour,minute
        Time of scheduled departure broken into hour and minutes.
- carrier
        Two letter carrier abbreviation. See airlines() to get name
- tailnum
        Plane tail number
- flight
        Flight number
- origin,dest
        Origin and destination. See airports() for additional metadata.
- air_time
        Amount of time spent in the air, in minutes
- distance
        Distance between airports, in miles
- time_hour
        Scheduled date and hour of the flight as a date. Along with origin, can be used to join flights data to weather data.

In [36]:
# use describe() to summarize all columns
flights.describe(include='all')

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,distance,hour,minute,time_hour,dep_time_mins,sched_dep_time_mins,arrd_time_mins,dep_delay_calc,arr_time_mins,airdep_time_diff
count,336776.0,336776.000000,336776.000000,328521.000000,336776.000000,328521.000000,328063.000000,336776.000000,327346.000000,336776,...,336776.000000,336776.000000,336776.000000,336776,328521.000000,336776.000000,328063.000000,328521.00000,328063.000000,328063.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,...,NaN,NaN,NaN,6936,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA,...,NaN,NaN,NaN,2013-09-13T12:00:00Z,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58665,...,NaN,NaN,NaN,94,NaN,NaN,NaN,NaN,NaN,NaN
mean,2013.0,6.548510,15.710787,1349.109947,1344.254840,12.639070,1502.054999,1536.380220,6.895377,NaN,...,1039.912604,13.180247,26.230100,NaN,822.168169,817.044944,913.020819,7.34845,913.020819,137.676855
std,0.0,3.414457,8.768607,488.281791,467.335756,40.210061,533.264132,497.457142,44.633292,NaN,...,733.233033,4.661316,19.300846,NaN,292.730990,281.147222,320.172755,86.99798,320.172755,50.700815
min,2013.0,1.000000,1.000000,1.000000,106.000000,-43.000000,1.000000,1.000000,-86.000000,NaN,...,17.000000,1.000000,0.000000,NaN,1.000000,66.000000,1.000000,-1438.00000,1.000000,33.000000
25%,2013.0,4.000000,8.000000,907.000000,906.000000,-5.000000,1104.000000,1124.000000,-17.000000,NaN,...,502.000000,9.000000,8.000000,NaN,547.000000,546.000000,664.000000,-5.00000,664.000000,95.000000
50%,2013.0,7.000000,16.000000,1401.000000,1359.000000,-2.000000,1535.000000,1556.000000,-5.000000,NaN,...,872.000000,13.000000,29.000000,NaN,841.000000,839.000000,935.000000,-2.00000,935.000000,138.000000
75%,2013.0,10.000000,23.000000,1744.000000,1729.000000,11.000000,1940.000000,1945.000000,14.000000,NaN,...,1389.000000,17.000000,44.000000,NaN,1064.000000,1049.000000,1180.000000,10.00000,1180.000000,174.000000
max,2013.0,12.000000,31.000000,2400.000000,2359.000000,1301.000000,2400.000000,2359.000000,1272.000000,NaN,...,4983.000000,23.000000,59.000000,NaN,1440.000000,1439.000000,1440.000000,911.00000,1440.000000,1165.000000

## Question 1. Selecting rows

From the 'flights' dataframe, find all flights that satisfy the following certain conditions:

In [37]:
# Had an arrival delay of two or more hours
flights[flights['arr_delay']>=120]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,distance,hour,minute,time_hour,dep_time_mins,sched_dep_time_mins,arrd_time_mins,dep_delay_calc,arr_time_mins,airdep_time_diff
119,2013,1,1,811.0,630,101.0,1047.0,830,137.0,MQ,...,544,6,30,2013-01-01T11:00:00Z,491.0,390,647.0,101.0,647.0,156.0
151,2013,1,1,848.0,1835,853.0,1001.0,1950,851.0,MQ,...,184,18,35,2013-01-01T23:00:00Z,528.0,1115,601.0,-587.0,601.0,73.0
218,2013,1,1,957.0,733,144.0,1056.0,853,123.0,UA,...,200,7,33,2013-01-01T12:00:00Z,597.0,453,656.0,144.0,656.0,59.0
268,2013,1,1,1114.0,900,134.0,1447.0,1222,145.0,UA,...,1416,9,0,2013-01-01T14:00:00Z,674.0,540,887.0,134.0,887.0,213.0
447,2013,1,1,1505.0,1310,115.0,1638.0,1431,127.0,EV,...,277,13,10,2013-01-01T18:00:00Z,905.0,790,998.0,115.0,998.0,93.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336579,2013,9,30,1823.0,1545,158.0,1934.0,1733,121.0,9E,...,765,15,45,2013-09-30T19:00:00Z,1103.0,945,1174.0,158.0,1174.0,71.0
336668,2013,9,30,1951.0,1649,182.0,2157.0,1903,174.0,EV,...,708,16,49,2013-09-30T20:00:00Z,1191.0,1009,1317.0,182.0,1317.0,126.0
336724,2013,9,30,2053.0,1815,158.0,2310.0,2054,136.0,EV,...,746,18,15,2013-09-30T22:00:00Z,1253.0,1095,1390.0,158.0,1390.0,137.0
336757,2013,9,30,2159.0,1845,194.0,2344.0,2030,194.0,9E,...,301,18,45,2013-09-30T22:00:00Z,1319.0,1125,1424.0,194.0,1424.0,105.0
336763,2013,9,30,2235.0,2001,154.0,59.0,2249,130.0,B6,...,944,20,1,2013-10-01T00:00:00Z,1355.0,1201,59.0,154.0,59.0,144.0

In [38]:
# Flew to Houston (IAH or HOU)
flights[flights["dest"].isin(['IAH', 'HOU'])]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,distance,hour,minute,time_hour,dep_time_mins,sched_dep_time_mins,arrd_time_mins,dep_delay_calc,arr_time_mins,airdep_time_diff
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,...,1400,5,15,2013-01-01T10:00:00Z,317.0,315,510.0,2.0,510.0,193.0
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,...,1416,5,29,2013-01-01T10:00:00Z,333.0,329,530.0,4.0,530.0,197.0
32,2013,1,1,623.0,627,-4.0,933.0,932,1.0,UA,...,1416,6,27,2013-01-01T11:00:00Z,383.0,387,573.0,-4.0,573.0,190.0
81,2013,1,1,728.0,732,-4.0,1041.0,1038,3.0,UA,...,1416,7,32,2013-01-01T12:00:00Z,448.0,452,641.0,-4.0,641.0,193.0
89,2013,1,1,739.0,739,0.0,1104.0,1038,26.0,UA,...,1400,7,39,2013-01-01T12:00:00Z,459.0,459,664.0,0.0,664.0,205.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336524,2013,9,30,1729.0,1720,9.0,2001.0,2010,-9.0,UA,...,1400,17,20,2013-09-30T21:00:00Z,1049.0,1040,1201.0,9.0,1201.0,152.0
336527,2013,9,30,1735.0,1715,20.0,2010.0,2005,5.0,WN,...,1411,17,15,2013-09-30T21:00:00Z,1055.0,1035,1210.0,20.0,1210.0,155.0
336618,2013,9,30,1859.0,1859,0.0,2134.0,2159,-25.0,UA,...,1416,18,59,2013-09-30T22:00:00Z,1139.0,1139,1294.0,0.0,1294.0,155.0
336694,2013,9,30,2015.0,2015,0.0,2244.0,2307,-23.0,UA,...,1400,20,15,2013-10-01T00:00:00Z,1215.0,1215,1364.0,0.0,1364.0,149.0
336737,2013,9,30,2105.0,2106,-1.0,2329.0,2354,-25.0,UA,...,1400,21,6,2013-10-01T01:00:00Z,1265.0,1266,1409.0,-1.0,1409.0,144.0

In [39]:
# Were operated by United (UA), American (AA), or Delta (DL)
flights[flights["carrier"].isin(['UA', 'AA','DL'])]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,distance,hour,minute,time_hour,dep_time_mins,sched_dep_time_mins,arrd_time_mins,dep_delay_calc,arr_time_mins,airdep_time_diff
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,...,1400,5,15,2013-01-01T10:00:00Z,317.0,315,510.0,2.0,510.0,193.0
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,...,1416,5,29,2013-01-01T10:00:00Z,333.0,329,530.0,4.0,530.0,197.0
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,...,1089,5,40,2013-01-01T10:00:00Z,342.0,340,563.0,2.0,563.0,221.0
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,...,762,6,0,2013-01-01T11:00:00Z,354.0,360,492.0,-6.0,492.0,138.0
5,2013,1,1,554.0,558,-4.0,740.0,728,12.0,UA,...,719,5,58,2013-01-01T10:00:00Z,354.0,358,460.0,-4.0,460.0,106.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336737,2013,9,30,2105.0,2106,-1.0,2329.0,2354,-25.0,UA,...,1400,21,6,2013-10-01T01:00:00Z,1265.0,1266,1409.0,-1.0,1409.0,144.0
336744,2013,9,30,2121.0,2100,21.0,2349.0,14,-25.0,DL,...,2475,21,0,2013-10-01T01:00:00Z,1281.0,1260,1429.0,21.0,1429.0,148.0
336751,2013,9,30,2140.0,2140,0.0,10.0,40,-30.0,AA,...,2475,21,40,2013-10-01T01:00:00Z,1300.0,1300,10.0,0.0,10.0,150.0
336755,2013,9,30,2149.0,2156,-7.0,2245.0,2308,-23.0,UA,...,200,21,56,2013-10-01T01:00:00Z,1309.0,1316,1365.0,-7.0,1365.0,56.0
336762,2013,9,30,2233.0,2113,80.0,112.0,30,42.0,UA,...,2565,21,13,2013-10-01T01:00:00Z,1353.0,1273,72.0,80.0,72.0,159.0

In [40]:
# Departed in July, August, and September
flights[flights["month"].isin([7, 8, 9])]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,distance,hour,minute,time_hour,dep_time_mins,sched_dep_time_mins,arrd_time_mins,dep_delay_calc,arr_time_mins,airdep_time_diff
250450,2013,7,1,1.0,2029,212.0,236.0,2359,157.0,B6,...,2586,20,29,2013-07-02T00:00:00Z,1.0,1229,156.0,-1228.0,156.0,155.0
250451,2013,7,1,2.0,2359,3.0,344.0,344,0.0,B6,...,1598,23,59,2013-07-02T03:00:00Z,2.0,1439,224.0,-1437.0,224.0,222.0
250452,2013,7,1,29.0,2245,104.0,151.0,1,110.0,B6,...,266,22,45,2013-07-02T02:00:00Z,29.0,1365,111.0,-1336.0,111.0,82.0
250453,2013,7,1,43.0,2130,193.0,322.0,14,188.0,B6,...,1076,21,30,2013-07-02T01:00:00Z,43.0,1290,202.0,-1247.0,202.0,159.0
250454,2013,7,1,44.0,2150,174.0,300.0,100,120.0,AA,...,2475,21,50,2013-07-02T01:00:00Z,44.0,1310,180.0,-1266.0,180.0,136.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,...,213,14,55,2013-09-30T18:00:00Z,NaN,895,NaN,NaN,NaN,NaN
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,...,198,22,0,2013-10-01T02:00:00Z,NaN,1320,NaN,NaN,NaN,NaN
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,...,764,12,10,2013-09-30T16:00:00Z,NaN,730,NaN,NaN,NaN,NaN
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,...,419,11,59,2013-09-30T15:00:00Z,NaN,719,NaN,NaN,NaN,NaN
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,...,431,8,40,2013-09-30T12:00:00Z,NaN,520,NaN,NaN,NaN,NaN

In [41]:
# Arrived more than two hours late, but didn’t leave late
flights[(flights['arr_delay'] >= 120) & (flights['dep_delay'] <= 0)]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,distance,hour,minute,time_hour,dep_time_mins,sched_dep_time_mins,arrd_time_mins,dep_delay_calc,arr_time_mins,airdep_time_diff
22911,2013,1,27,1419.0,1420,-1.0,1754.0,1550,124.0,MQ,...,719,14,20,2013-01-27T19:00:00Z,859.0,860,1074.0,-1.0,1074.0,215.0
33011,2013,10,7,1350.0,1350,0.0,1736.0,1526,130.0,EV,...,812,13,50,2013-10-07T17:00:00Z,830.0,830,1056.0,0.0,1056.0,226.0
33019,2013,10,7,1357.0,1359,-2.0,1858.0,1654,124.0,AA,...,1389,13,59,2013-10-07T17:00:00Z,837.0,839,1138.0,-2.0,1138.0,301.0
41075,2013,10,16,657.0,700,-3.0,1258.0,1056,122.0,B6,...,1598,7,0,2013-10-16T11:00:00Z,417.0,420,778.0,-3.0,778.0,361.0
55985,2013,11,1,658.0,700,-2.0,1329.0,1015,194.0,VX,...,2475,7,0,2013-11-01T11:00:00Z,418.0,420,809.0,-2.0,809.0,391.0
152766,2013,3,18,1844.0,1847,-3.0,39.0,2219,140.0,UA,...,2586,18,47,2013-03-18T22:00:00Z,1124.0,1127,39.0,-3.0,39.0,355.0
180893,2013,4,17,1635.0,1640,-5.0,2049.0,1845,124.0,MQ,...,502,16,40,2013-04-17T20:00:00Z,995.0,1000,1249.0,-5.0,1249.0,254.0
181270,2013,4,18,558.0,600,-2.0,1149.0,850,179.0,AA,...,1389,6,0,2013-04-18T10:00:00Z,358.0,360,709.0,-2.0,709.0,351.0
181327,2013,4,18,655.0,700,-5.0,1213.0,950,143.0,AA,...,1372,7,0,2013-04-18T11:00:00Z,415.0,420,733.0,-5.0,733.0,318.0
213693,2013,5,22,1827.0,1830,-3.0,2217.0,2010,127.0,MQ,...,419,18,30,2013-05-22T22:00:00Z,1107.0,1110,1337.0,-3.0,1337.0,230.0
214512,2013,5,23,1810.0,1810,0.0,2208.0,2000,128.0,MQ,...,479,18,10,2013-05-23T22:00:00Z,1090.0,1090,1328.0,0.0,1328.0,238.0
226434,2013,6,5,1604.0,1615,-11.0,2041.0,1840,121.0,MQ,...,762,16,15,2013-06-05T20:00:00Z,964.0,975,1241.0,-11.0,1241.0,277.0
235033,2013,6,14,1708.0,1710,-2.0,2227.0,2015,132.0,AA,...,2475,17,10,2013-06-14T21:00:00Z,1028.0,1030,1347.0,-2.0,1347.0,319.0
244329,2013,6,24,1602.0,1605,-3.0,2134.0,1916,138.0,DL,...,1521,16,5,2013-06-24T20:00:00Z,962.0,965,1294.0,-3.0,1294.0,332.0
247568,2013,6,27,2052.0,2100,-8.0,13.0,2210,123.0,US,...,184,21,0,2013-06-28T01:00:00Z,1252.0,1260,13.0,-8.0,13.0,201.0
249957,2013,6,30,1423.0,1425,-2.0,1816.0,1554,142.0,B6,...,301,14,25,2013-06-30T18:00:00Z,863.0,865,1096.0,-2.0,1096.0,233.0
250689,2013,7,1,905.0,905,0.0,1443.0,1223,140.0,DL,...,1096,9,5,2013-07-01T13:00:00Z,545.0,545,883.0,0.0,883.0,338.0
256340,2013,7,7,1659.0,1700,-1.0,2050.0,1823,147.0,US,...,214,17,0,2013-07-07T21:00:00Z,1019.0,1020,1250.0,-1.0,1250.0,231.0
256358,2013,7,7,1727.0,1730,-3.0,2203.0,1951,132.0,F9,...,1620,17,30,2013-07-07T21:00:00Z,1047.0,1050,1323.0,-3.0,1323.0,276.0
256373,2013,7,7,1746.0,1755,-9.0,2133.0,1921,132.0,B6,...,228,17,55,2013-07-07T21:00:00Z,1066.0,1075,1293.0,-9.0,1293.0,227.0
256405,2013,7,7,1823.0,1830,-7.0,2201.0,1955,126.0,MQ,...,764,18,30,2013-07-07T22:00:00Z,1103.0,1110,1321.0,-7.0,1321.0,218.0
270742,2013,7,22,1555.0,1600,-5.0,2139.0,1938,121.0,DL,...,2586,16,0,2013-07-22T20:00:00Z,955.0,960,1299.0,-5.0,1299.0,344.0
270752,2013,7,22,1606.0,1615,-9.0,2056.0,1831,145.0,DL,...,1020,16,15,2013-07-22T20:00:00Z,966.0,975,1256.0,-9.0,1256.0,290.0
270762,2013,7,22,1628.0,1630,-2.0,2151.0,1939,132.0,B6,...,2475,16,30,2013-07-22T20:00:00Z,988.0,990,1311.0,-2.0,1311.0,323.0
276564,2013,7,28,1710.0,1711,-1.0,2248.0,2039,129.0,B6,...,2576,17,11,2013-07-28T21:00:00Z,1030.0,1031,1368.0,-1.0,1368.0,338.0
287148,2013,8,8,1457.0,1500,-3.0,1828.0,1624,124.0,US,...,214,15,0,2013-08-08T19:00:00Z,897.0,900,1108.0,-3.0,1108.0,211.0
291439,2013,8,13,657.0,659,-2.0,1015.0,814,121.0,EV,...,748,6,59,2013-08-13T10:00:00Z,417.0,419,615.0,-2.0,615.0,198.0
305985,2013,8,28,1157.0,1200,-3.0,1520.0,1316,124.0,US,...,214,12,0,2013-08-28T16:00:00Z,717.0,720,920.0,-3.0,920.0,203.0
325764,2013,9,19,656.0,700,-4.0,1037.0,833,124.0,UA,...,733,7,0,2013-09-19T11:00:00Z,416.0,420,637.0,-4.0,637.0,221.0

In [42]:
# Were delayed by at least an hour, but made up over 30 minutes in flight
flights[(flights['dep_delay'] >= 60) & ((flights['dep_delay'] - flights['arr_delay'])>30)]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,distance,hour,minute,time_hour,dep_time_mins,sched_dep_time_mins,arrd_time_mins,dep_delay_calc,arr_time_mins,airdep_time_diff
815,2013,1,1,2205.0,1720,285.0,46.0,2040,246.0,AA,...,1085,17,20,2013-01-01T22:00:00Z,1325.0,1040,46.0,285.0,46.0,161.0
832,2013,1,1,2326.0,2130,116.0,131.0,18,73.0,B6,...,2248,21,30,2013-01-02T02:00:00Z,1406.0,1290,91.0,116.0,91.0,125.0
2286,2013,1,3,1503.0,1221,162.0,1803.0,1555,128.0,UA,...,2565,12,21,2013-01-03T17:00:00Z,903.0,741,1083.0,162.0,1083.0,180.0
2508,2013,1,3,1839.0,1700,99.0,2056.0,1950,66.0,AA,...,1747,17,0,2013-01-03T22:00:00Z,1119.0,1020,1256.0,99.0,1256.0,137.0
2522,2013,1,3,1850.0,1745,65.0,2148.0,2120,28.0,AA,...,2586,17,45,2013-01-03T22:00:00Z,1130.0,1065,1308.0,65.0,1308.0,178.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336572,2013,9,30,1818.0,1715,63.0,2001.0,1940,21.0,9E,...,1113,17,15,2013-09-30T21:00:00Z,1098.0,1035,1201.0,63.0,1201.0,103.0
336579,2013,9,30,1823.0,1545,158.0,1934.0,1733,121.0,9E,...,765,15,45,2013-09-30T19:00:00Z,1103.0,945,1174.0,158.0,1174.0,71.0
336674,2013,9,30,1956.0,1825,91.0,2208.0,2121,47.0,DL,...,2446,18,25,2013-09-30T22:00:00Z,1196.0,1105,1328.0,91.0,1328.0,132.0
336704,2013,9,30,2028.0,1910,78.0,2255.0,2215,40.0,AA,...,2475,19,10,2013-09-30T23:00:00Z,1228.0,1150,1375.0,78.0,1375.0,147.0
336762,2013,9,30,2233.0,2113,80.0,112.0,30,42.0,UA,...,2565,21,13,2013-10-01T01:00:00Z,1353.0,1273,72.0,80.0,72.0,159.0

In [43]:
# Departed between midnight and 6am (inclusive)
flights[(flights['dep_time'] >= 0) & (flights['dep_time'] <= 600)]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,distance,hour,minute,time_hour,dep_time_mins,sched_dep_time_mins,arrd_time_mins,dep_delay_calc,arr_time_mins,airdep_time_diff
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,...,1400,5,15,2013-01-01T10:00:00Z,317.0,315,510.0,2.0,510.0,193.0
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,...,1416,5,29,2013-01-01T10:00:00Z,333.0,329,530.0,4.0,530.0,197.0
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,...,1089,5,40,2013-01-01T10:00:00Z,342.0,340,563.0,2.0,563.0,221.0
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,...,1576,5,45,2013-01-01T10:00:00Z,344.0,345,604.0,-1.0,604.0,260.0
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,...,762,6,0,2013-01-01T11:00:00Z,354.0,360,492.0,-6.0,492.0,138.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335802,2013,9,30,557.0,600,-3.0,852.0,923,-31.0,UA,...,2586,6,0,2013-09-30T10:00:00Z,357.0,360,532.0,-3.0,532.0,175.0
335803,2013,9,30,558.0,600,-2.0,815.0,829,-14.0,EV,...,746,6,0,2013-09-30T10:00:00Z,358.0,360,495.0,-2.0,495.0,137.0
335804,2013,9,30,558.0,600,-2.0,742.0,749,-7.0,DL,...,502,6,0,2013-09-30T10:00:00Z,358.0,360,462.0,-2.0,462.0,104.0
335805,2013,9,30,559.0,600,-1.0,NaN,715,NaN,WN,...,711,6,0,2013-09-30T10:00:00Z,359.0,360,NaN,-1.0,NaN,NaN
335806,2013,9,30,600.0,600,0.0,844.0,856,-12.0,B6,...,1069,6,0,2013-09-30T10:00:00Z,360.0,360,524.0,0.0,524.0,164.0

In [44]:
# How many flights have a missing dep_time?
int(flights['dep_time'].isnull().sum())

8255

## Question 2. Sorting

In [45]:
# Sort flights to find the least delayed flights. Find the flights that left earliest.
display(flights.sort_values(by='dep_delay',ascending=True).head())

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,distance,hour,minute,time_hour,dep_time_mins,sched_dep_time_mins,arrd_time_mins,dep_delay_calc,arr_time_mins,airdep_time_diff
89673,2013,12,7,2040.0,2123,-43.0,40.0,2352,48.0,B6,...,1626,21,23,2013-12-08T02:00:00Z,1240.0,1283,40.0,-43.0,40.0,240.0
113633,2013,2,3,2022.0,2055,-33.0,2240.0,2338,-58.0,DL,...,1183,20,55,2013-02-04T01:00:00Z,1222.0,1255,1360.0,-33.0,1360.0,138.0
64501,2013,11,10,1408.0,1440,-32.0,1549.0,1559,-10.0,EV,...,229,14,40,2013-11-10T19:00:00Z,848.0,880,949.0,-32.0,949.0,101.0
9619,2013,1,11,1900.0,1930,-30.0,2233.0,2243,-10.0,DL,...,1010,19,30,2013-01-12T00:00:00Z,1140.0,1170,1353.0,-30.0,1353.0,213.0
24915,2013,1,29,1703.0,1730,-27.0,1947.0,1957,-10.0,F9,...,1620,17,30,2013-01-29T22:00:00Z,1023.0,1050,1187.0,-27.0,1187.0,164.0

In [46]:
# Which flights travelled the farthest? Which travelled the shortest?
display(flights.sort_values(by='distance',ascending=False).head())
display(flights.sort_values(by='distance',ascending=True).head())

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,distance,hour,minute,time_hour,dep_time_mins,sched_dep_time_mins,arrd_time_mins,dep_delay_calc,arr_time_mins,airdep_time_diff
118311,2013,2,9,1206.0,900,186.0,1814.0,1540,154.0,HA,...,4983,9,0,2013-02-09T14:00:00Z,726.0,540,1094.0,186.0,1094.0,368.0
227103,2013,6,6,1044.0,1000,44.0,1441.0,1435,6.0,HA,...,4983,10,0,2013-06-06T14:00:00Z,644.0,600,881.0,44.0,881.0,237.0
224146,2013,6,3,957.0,1000,-3.0,1432.0,1435,-3.0,HA,...,4983,10,0,2013-06-03T14:00:00Z,597.0,600,872.0,-3.0,872.0,275.0
170226,2013,4,6,957.0,1000,-3.0,1510.0,1510,0.0,HA,...,4983,10,0,2013-04-06T14:00:00Z,597.0,600,910.0,-3.0,910.0,313.0
130088,2013,2,22,857.0,900,-3.0,1436.0,1540,-64.0,HA,...,4983,9,0,2013-02-22T14:00:00Z,537.0,540,876.0,-3.0,876.0,339.0

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,distance,hour,minute,time_hour,dep_time_mins,sched_dep_time_mins,arrd_time_mins,dep_delay_calc,arr_time_mins,airdep_time_diff
275945,2013,7,27,NaN,106,NaN,NaN,245,NaN,US,...,17,1,6,2013-07-27T05:00:00Z,NaN,66,NaN,NaN,NaN,NaN
116412,2013,2,6,2125.0,2129,-4.0,2207.0,2224,-17.0,EV,...,80,21,29,2013-02-07T02:00:00Z,1285.0,1289,1327.0,-4.0,1327.0,42.0
164109,2013,3,30,1942.0,1950,-8.0,2026.0,2044,-18.0,EV,...,80,19,50,2013-03-30T23:00:00Z,1182.0,1190,1226.0,-8.0,1226.0,44.0
150994,2013,3,16,1947.0,1950,-3.0,2055.0,2044,11.0,EV,...,80,19,50,2013-03-16T23:00:00Z,1187.0,1190,1255.0,-3.0,1255.0,68.0
19088,2013,1,22,2203.0,2130,33.0,2317.0,2225,52.0,EV,...,80,21,30,2013-01-23T02:00:00Z,1323.0,1290,1397.0,33.0,1397.0,74.0

## Question 3. Selecting Columns

Use at least three ways to select dep_time, dep_delay, arr_time, and arr_delay from flights.

In [47]:
# Method 1
flights.loc[:,['dep_time','dep_delay','arr_time','arr_delay']]

        dep_time  dep_delay  arr_time  arr_delay
0          517.0        2.0     830.0       11.0
1          533.0        4.0     850.0       20.0
2          542.0        2.0     923.0       33.0
3          544.0       -1.0    1004.0      -18.0
4          554.0       -6.0     812.0      -25.0
...          ...        ...       ...        ...
336771       NaN        NaN       NaN        NaN
336772       NaN        NaN       NaN        NaN
336773       NaN        NaN       NaN        NaN
336774       NaN        NaN       NaN        NaN
336775       NaN        NaN       NaN        NaN

[336776 rows x 4 columns]

In [48]:
# Method 2
flights.iloc[:,[3,5,6,7]]

        dep_time  dep_delay  arr_time  sched_arr_time
0          517.0        2.0     830.0             819
1          533.0        4.0     850.0             830
2          542.0        2.0     923.0             850
3          544.0       -1.0    1004.0            1022
4          554.0       -6.0     812.0             837
...          ...        ...       ...             ...
336771       NaN        NaN       NaN            1634
336772       NaN        NaN       NaN            2312
336773       NaN        NaN       NaN            1330
336774       NaN        NaN       NaN            1344
336775       NaN        NaN       NaN            1020

[336776 rows x 4 columns]

In [49]:
# Method 3
flights[['dep_time','dep_delay','arr_time','arr_delay']]

        dep_time  dep_delay  arr_time  arr_delay
0          517.0        2.0     830.0       11.0
1          533.0        4.0     850.0       20.0
2          542.0        2.0     923.0       33.0
3          544.0       -1.0    1004.0      -18.0
4          554.0       -6.0     812.0      -25.0
...          ...        ...       ...        ...
336771       NaN        NaN       NaN        NaN
336772       NaN        NaN       NaN        NaN
336773       NaN        NaN       NaN        NaN
336774       NaN        NaN       NaN        NaN
336775       NaN        NaN       NaN        NaN

[336776 rows x 4 columns]

## Question 4. Adding new columns

Currently dep_time and sched_dep_time are convenient to look at, but hard to compute with because they’re not really continuous numbers.

For example, 759 means 7:59 and 801 means 8:01. Their difference is not 42 but 2 minutes.

In [50]:
# Convert them to a more convenient representation of number of minutes since midnight (0).
flights['dep_time_mins'] = (flights['dep_time']//100)*60 + (flights['dep_time']%100)
flights['sched_dep_time_mins'] = (flights['sched_dep_time']//100)*60 + (flights['sched_dep_time']%100)

In [51]:
# Create a new column of arr_time - dep_time.
flights['arr_time_mins'] = (flights['arr_time']//100)*60 + (flights['arr_time']%100)
flights['airdep_time_diff'] = (flights['arr_time_mins']-flights['dep_time_mins'])%1440

# Compare this column with air_time.
flights[['airdep_time_diff', 'air_time']].head(10)

   airdep_time_diff  air_time
0             193.0     227.0
1             197.0     227.0
2             221.0     160.0
3             260.0     183.0
4             138.0     116.0
5             106.0     150.0
6             198.0     158.0
7              72.0      53.0
8             161.0     140.0
9             115.0     138.0

In [52]:
# Compare dep_time, sched_dep_time, and dep_delay. How would you expect those three numbers to be related?
# Try creating a column to calculate dep_delay from dep_time and sched_dep_time (and/or other columns if necessary).
flights['dep_delay_calc'] = flights['dep_time_mins']-flights['sched_dep_time_mins']

# Test your results.
flights[['dep_delay_calc', 'dep_delay']].head(10)

   dep_delay_calc  dep_delay
0             2.0        2.0
1             4.0        4.0
2             2.0        2.0
3            -1.0       -1.0
4            -6.0       -6.0
5            -4.0       -4.0
6            -5.0       -5.0
7            -3.0       -3.0
8            -3.0       -3.0
9            -2.0       -2.0

## Question 5. Mixing things together

The following questions may require multiple operations above.

In [53]:
# Find the 20 most delayed flights.
# Display the following: year,month,day,carrier,flight,dep_delay,arr_delay,carrier
# How do you want to handle ties?
sortedflights = flights.sort_values(by=['dep_delay', 'arr_delay'], ascending=False).head(20)
cols = ['year', 'month', 'day', 'carrier', 'flight', 'dep_delay', 'arr_delay', 'carrier']
sortedflights[cols]

        year  month  day carrier  flight  dep_delay  arr_delay carrier
7072    2013      1    9      HA      51     1301.0     1272.0      HA
235778  2013      6   15      MQ    3535     1137.0     1127.0      MQ
8239    2013      1   10      MQ    3695     1126.0     1109.0      MQ
327043  2013      9   20      AA     177     1014.0     1007.0      AA
270376  2013      7   22      MQ    3075     1005.0      989.0      MQ
173992  2013      4   10      DL    2391      960.0      931.0      DL
151974  2013      3   17      DL    2119      911.0      915.0      DL
247040  2013      6   27      DL    2007      899.0      850.0      DL
270987  2013      7   22      DL    2047      898.0      895.0      DL
87238   2013     12    5      AA     172      896.0      878.0      AA
195711  2013      5    3      MQ    3744      878.0      875.0      MQ
210174  2013      5   19      AA     257      853.0      852.0      AA
151     2013      1    1      MQ    3944      853.0      851.0      MQ
119784  2013      2   10      F9     835      853.0      834.0      F9
99938   2013     12   19      DL    1223      849.0      847.0      DL
98014   2013     12   17      AA     172      845.0      846.0      AA
95530   2013     12   14      DL    2391      825.0      856.0      DL
182478  2013      4   19      DL    1435      812.0      821.0      DL
246911  2013      6   27      AA    2019      803.0      802.0      AA
152312  2013      3   18      DL    2363      800.0      784.0      DL

In [54]:
# Sort all AA flights to find the top 10 fastest (highest speed) flights.
# Display the following: year,month,day,carrier,flight,orig,dest,distance,air_time,speed (miles per hour)
AAflights=flights[flights["carrier"].isin(['AA'])].copy()
AAflights['speed'] = (AAflights['distance']/AAflights['air_time'])*60
AAflights.sort_values(by='speed', ascending =False)
cols=['year', 'month', 'day', 'carrier', 'flight', 'origin', 'dest', 'distance', 'air_time', 'speed']
AAflights.sort_values(by='speed',ascending=False)[cols].head(10)

,year,month,day,carrier,flight,origin,dest,distance,air_time,speed
70704,2013,11,17,AA,936,JFK,STT,1623,175.0,556.457143
87723,2013,12,5,AA,1029,JFK,SJU,1598,173.0,554.219653
119700,2013,2,10,AA,1613,JFK,SJU,1598,173.0,554.219653
129686,2013,2,21,AA,1613,JFK,SJU,1598,174.0,551.034483
87575,2013,12,5,AA,95,JFK,SJU,1598,175.0,547.885714
144408,2013,3,9,AA,1613,JFK,SJU,1598,176.0,544.772727
70721,2013,11,17,AA,1357,JFK,SJU,1598,176.0,544.772727
70335,2013,11,16,AA,95,JFK,SJU,1598,177.0,541.694915
119477,2013,2,10,AA,1635,JFK,SJU,1598,177.0,541.694915
119894,2013,2,11,AA,413,JFK,SJU,1598,177.0,541.694915

In [55]:
# Find all flights that satisfy the following:
# - From John F. Kennedy Airpot (JFK) or Newark Aiport (EWR) to Seattle-Tacoma Airport (SEA)
# - Carrier is UA, AA, or DL.
# - Dates from 4/1/2013 (inclusive) to 4/3/2013 (inclusive)
# - Scheduled arrival time is before noon.
# - Display the following: year,month,day,carrier,flight,origin,dest,sched_dep_time,sched_arr_time
# - Sort by year, month, day, sched_arr_time
allflights = flights[(flights['origin'].isin(['JFK','EWR'])) &
                     (flights['dest'] == 'SEA') &
                     (flights['carrier'].isin(['UA','AA','DL'])) &
                     (flights['month'] == 4) &
                     (flights['day']).between(1,3) &
                     (flights['sched_arr_time']<1200)]
allflightssorted=allflights[['year','month','day','carrier','flight','origin','dest','sched_dep_time','sched_arr_time']].sort_values(['year','month','day','sched_arr_time'])
allflightssorted

,year,month,day,carrier,flight,origin,dest,sched_dep_time,sched_arr_time
165210,2013,4,1,DL,183,JFK,SEA,745,1100
166180,2013,4,2,DL,183,JFK,SEA,745,1100
167168,2013,4,3,DL,183,JFK,SEA,745,1100